CREATE OR REPLACE FUNCTION FIND_BY_VALUE_TOKEN(
    _value TEXT
) RETURNS SETOF TOKEN
LANGUAGE plpgsql    
AS $$
BEGIN
    RETURN QUERY
        SELECT * FROM TOKEN
        WHERE VALUE = _value;
END;$$;