CREATE OR REPLACE FUNCTION FIND_BY_TOKEN_TOKEN(
    _token TEXT
) RETURNS SETOF TOKEN
LANGUAGE plpgsql    
AS $$
BEGIN
    RETURN QUERY
        SELECT * FROM TOKEN
        WHERE TOKEN = _token;
END;$$;