CREATE OR REPLACE FUNCTION FIND_BY_USER_ID_TOKEN(
    _user_id INT
) RETURNS SETOF TOKEN
LANGUAGE plpgsql    
AS $$
BEGIN
    RETURN QUERY
        SELECT * FROM TOKEN
        WHERE AUTH_USER_ID = _user_id;
END;$$;