DROP TABLE IF EXISTS BLOG CASCADE;

CREATE TABLE BLOG(
   ID          SERIAL PRIMARY KEY,
   AUTHOR_ID   INT REFERENCES AUTHOR (ID) NOT NULL,
   TITLE       CHAR(50)                   NOT NULL,
   DESCRIPTION TEXT                       NOT NULL   
);