DROP TABLE IF EXISTS POST_POST_REF CASCADE;

CREATE TABLE POST_POST_REF(
   ID          SERIAL PRIMARY KEY,
   POST_ID     INT REFERENCES POST (ID) NOT NULL,
   POST_REF_ID INT REFERENCES POST (ID) NOT NULL
);