CREATE OR REPLACE FUNCTION FIND_BY_EMAIL_AUTH_USER(
    _email CHAR(50)
) RETURNS SETOF AUTH_USER
LANGUAGE plpgsql    
AS $$
BEGIN
    RETURN QUERY
        SELECT * FROM AUTH_USER
        WHERE EMAIL = _email;
END;$$;